server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.100.78.111:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: mall
    password: Mall@root.0

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
